-- Assert all 7 service slugs exist before seeding
DO $$
DECLARE
  missing_slugs text[];
BEGIN
  SELECT ARRAY_AGG(slug) INTO missing_slugs
  FROM (VALUES ('hybrid'),('ongrid'),('bess'),('pump'),('ev'),('ups'),('controller')) AS required(slug)
  WHERE NOT EXISTS (SELECT 1 FROM services s WHERE s.slug = required.slug);

  IF missing_slugs IS NOT NULL THEN
    RAISE EXCEPTION 'Missing service slugs: %', missing_slugs;
  END IF;
END;
$$;

-- hybrid
INSERT INTO service_details (service_id, tagline, overview, what_is_it, how_it_works, benefits, use_cases, specs, sources)
SELECT
  s.id,
  'The best of both worlds — solar power, battery backup, and grid connection in one unified system.',
  'A hybrid solar system combines solar panels, a battery storage bank, and a grid connection to give you maximum flexibility, reliability, and savings. It is the most versatile solar setup available — powering your home or business during the day from solar, storing excess energy for nighttime use, and drawing from the grid only when needed.',
  $$A hybrid solar system is a grid-tied photovoltaic (PV) installation that also includes a battery energy storage system (BESS). Unlike a purely on-grid system that shuts down during outages, or a fully off-grid system that relies entirely on batteries, a hybrid system intelligently manages three energy sources — your solar array, your battery bank, and the utility grid. A hybrid inverter acts as the brain, routing power between these sources based on availability and demand. In the Philippines, hybrid systems typically pair a Sofar, Solax, or Deye inverter with lithium iron phosphate (LFP) batteries to deliver 24/7 reliable power even during brownouts.$$,
  '[{"step":"Solar Generation","description":"Photovoltaic panels on your roof or ground mount convert sunlight into DC electricity. Output depends on panel wattage, roof orientation, and sunlight hours — Leyte averages 4.5–5.5 peak sun hours per day."},{"step":"Hybrid Inverter Conversion","description":"The hybrid inverter converts DC power to AC for household use, simultaneously managing charging of the battery bank and synchronizing with the grid. It monitors all three sources in real time."},{"step":"Battery Charging & Storage","description":"Excess solar energy not consumed immediately is stored in lithium LFP batteries. A fully charged 10 kWh battery bank can power a typical Filipino home through the night and beyond."},{"step":"Grid Backup & Net Metering","description":"When batteries are full and solar is still producing, excess power is exported to the grid. When solar and battery are insufficient, the grid supplements — all managed automatically with zero manual switching."},{"step":"Blackout Protection","description":"During grid outages, the hybrid inverter islands your system and continues supplying power from solar and batteries — a capability that purely on-grid systems cannot provide."}]',
  '[{"iconName":"ShieldCheck","title":"Brownout Protection","description":"Battery backup keeps critical loads running during Visayas grid interruptions, which average 8–12 hours per month in some areas."},{"iconName":"TrendingDown","title":"Dramatically Lower Bills","description":"Most households eliminate 70–100% of their electric bill. A properly sized 6 kW hybrid system in Ormoc can save ₱4,000–₱8,000 per month."},{"iconName":"RefreshCw","title":"Net Metering Ready","description":"Export surplus power to VECO/LEYTE SAMAR ELECTRIC CO. and earn credits under the Philippine Net Metering Program (ERC Resolution No. 09, Series of 2013)."},{"iconName":"Leaf","title":"Zero Carbon Operation","description":"Reduce your household carbon footprint by up to 4 tonnes of CO₂ per year — equivalent to planting over 180 trees annually."},{"iconName":"Smartphone","title":"Remote Monitoring","description":"Monitor generation, battery state, and consumption in real time via mobile app (Sofar ME3000, Solax Cloud, or equivalent)."},{"iconName":"Banknote","title":"ROI in 4–7 Years","description":"With current electricity rates and system costs, most Philippine hybrid solar investments pay back in 4–7 years against a 25-year panel lifespan."}]',
  '[{"item":"Residential homes in areas with frequent brownouts"},{"item":"Small businesses and retail stores requiring 24/7 power"},{"item":"Home offices and remote workers dependent on stable internet and equipment"},{"item":"Properties in semi-rural areas with unstable grid supply"},{"item":"Homeowners wanting to future-proof against rising electricity tariffs"}]',
  '[{"label":"Typical System Size","value":"6 kW – 100 kW+"},{"label":"Battery Chemistry","value":"Lithium Iron Phosphate (LFP)"},{"label":"Battery Capacity","value":"5 kWh – 100 kWh+"},{"label":"Panel Type","value":"Monocrystalline PERC / TOPCon"},{"label":"Inverter Brands","value":"Sofar Solar, Solax Power, Deye"},{"label":"Battery Life","value":"10–15 years (>4,000 cycles at 80% DoD)"},{"label":"Panel Warranty","value":"25-year linear power output warranty"},{"label":"Installation Time","value":"1–3 days depending on system size"}]',
  '[{"title":"Net Metering Guidelines for Renewable Energy","url":"https://www.erc.gov.ph","publisher":"Energy Regulatory Commission (ERC) Philippines"},{"title":"Renewable Energy Act of 2008 (RA 9513)","url":"https://www.doe.gov.ph","publisher":"Department of Energy Philippines"},{"title":"Utility-Scale Battery Storage","url":"https://www.nrel.gov","publisher":"National Renewable Energy Laboratory (NREL)"},{"title":"Solar PV — Technology Brief","url":"https://www.irena.org","publisher":"International Renewable Energy Agency (IRENA)"},{"title":"Sofar Hybrid Inverter Product Documentation","url":"https://www.sofarsolar.com","publisher":"Sofar Solar"}]'
FROM services s WHERE s.slug = 'hybrid'
ON CONFLICT (service_id) DO NOTHING;

-- ongrid
INSERT INTO service_details (service_id, tagline, overview, what_is_it, how_it_works, benefits, use_cases, specs, sources)
SELECT
  s.id,
  'Feed the grid, earn credits, and slash your electricity bill — the simplest and most affordable solar option.',
  'An on-grid (grid-tied) solar system connects your solar panels directly to the utility grid without batteries. During the day, solar powers your home and any surplus is exported to the grid for credits. It is the most cost-effective solar installation because it removes the battery expense while still delivering significant monthly savings.',
  $$An on-grid solar system consists of solar panels wired to a grid-tied inverter, which converts DC electricity to grid-synchronized AC power. When your panels produce more electricity than you consume, the excess flows backward through your meter to the utility grid — a process called net metering. Under Philippine law (RA 9513 and ERC Net Metering Rules), distribution utilities like VECO are required to accept this surplus and credit you at the blended generation rate. At night or on cloudy days, you draw normally from the grid. There are no batteries, making this the simplest and lowest-cost solar option available.$$,
  '[{"step":"Solar Panel Generation","description":"Panels produce DC power proportional to sunlight intensity. A south-facing or flat roof in Leyte can generate 4–5 kWh per installed kWp on an average day."},{"step":"Grid-Tie Inverter Conversion","description":"A grid-tie inverter converts DC to AC at exactly the same frequency and phase as the grid (60 Hz in the Philippines). This synchronization is required for safe export."},{"step":"Load Priority","description":"Solar power first satisfies your own loads (appliances, lights, etc.). If generation exceeds consumption, surplus flows to the grid."},{"step":"Bidirectional Meter & Net Metering","description":"A DOE/ERC-approved bidirectional meter records both import and export. Your monthly bill deducts your export credits from your consumption, reducing the amount owed."},{"step":"Automatic Grid Safety Shutdown","description":"On-grid inverters include anti-islanding protection — they automatically shut down during grid outages for safety, restarting automatically when the grid is restored."}]',
  '[{"iconName":"Banknote","title":"Lowest Upfront Cost","description":"No batteries means 30–50% lower installation cost compared to hybrid systems. A 5 kW on-grid system in the Philippines typically costs ₱180,000–₱280,000 installed."},{"iconName":"Receipt","title":"Earn Bill Credits","description":"Exported kWh are credited at your utility''s blended generation rate. Homes with large daytime loads (offices, businesses) can achieve near-zero monthly bills."},{"iconName":"Timer","title":"Fastest Payback","description":"With no battery costs, on-grid systems can pay back in 3–5 years — the shortest ROI of any solar configuration at current Leyte electricity rates."},{"iconName":"Wrench","title":"Minimal Maintenance","description":"No moving parts, no battery replacement, no electrolyte checks. Panels require only occasional cleaning; inverters are rated for 10–15 years of service."},{"iconName":"Scale","title":"Scalable Design","description":"Start with a smaller system and add panels later. Batteries can be added at any time to upgrade to a hybrid setup as your needs or budget change."},{"iconName":"Globe","title":"Environmental Impact","description":"A 5 kW system offsets approximately 3 tonnes of CO₂ per year — the equivalent of removing one car from the road annually."}]',
  '[{"item":"Residential homes with stable grid supply and predictable daytime usage"},{"item":"Offices and commercial buildings operating primarily during daylight hours"},{"item":"Schools, churches, and community buildings with daytime-heavy loads"},{"item":"Businesses looking for the fastest return on solar investment"},{"item":"Properties where budget constraints make battery systems impractical"}]',
  '[{"label":"Typical System Size","value":"3 kW – 100 kW+"},{"label":"Inverter Type","value":"Grid-Tie (no battery port)"},{"label":"Panel Type","value":"Monocrystalline PERC / TOPCon"},{"label":"Net Metering Eligibility","value":"Up to 100 kW under RA 9513"},{"label":"Credit Rate","value":"Blended generation rate (utility-set)"},{"label":"Inverter Lifespan","value":"10–15 years"},{"label":"Panel Warranty","value":"25-year linear power output warranty"},{"label":"Grid Compliance","value":"DOE/ERC-compliant anti-islanding protection"}]',
  '[{"title":"Net Metering Rules and Regulations","url":"https://www.erc.gov.ph","publisher":"Energy Regulatory Commission (ERC) Philippines"},{"title":"Renewable Energy Act of 2008 (RA 9513)","url":"https://www.doe.gov.ph","publisher":"Department of Energy Philippines"},{"title":"Grid-Connected Photovoltaic Systems","url":"https://www.irena.org","publisher":"IRENA"},{"title":"Solar Photovoltaic System Basics","url":"https://www.nrel.gov","publisher":"NREL"}]'
FROM services s WHERE s.slug = 'ongrid'
ON CONFLICT (service_id) DO NOTHING;

-- bess
INSERT INTO service_details (service_id, tagline, overview, what_is_it, how_it_works, benefits, use_cases, specs, sources)
SELECT
  s.id,
  'Never lose power again — store solar energy and stay powered through any outage, day or night.',
  'A Battery Energy Storage System (BESS) stores electrical energy in lithium cells for use on demand. Paired with solar panels, a BESS lets you use free solar energy at night, ride through brownouts without interruption, and reduce dependence on the grid — making it the cornerstone of true energy independence.',
  'A BESS is a rechargeable battery system combined with a battery management system (BMS) and bidirectional inverter/charger. In a solar context, the BESS charges during peak solar generation hours and discharges to power loads when solar is insufficient or unavailable. Modern BESS units use lithium iron phosphate (LFP) chemistry — the safest, longest-lasting lithium battery chemistry available — with cycle lives exceeding 4,000 charge-discharge cycles at 80% depth of discharge. In the Philippines, BESS installations are increasingly common in both residential and commercial settings due to the high frequency of grid interruptions, particularly in Visayas and Mindanao.',
  '[{"step":"Charging from Solar","description":"The BESS charges when solar production exceeds immediate load demand. An MPPT charge controller or hybrid inverter manages the charge rate to protect battery health."},{"step":"Battery Management System (BMS)","description":"An embedded BMS monitors every cell in real time, balancing charge levels, preventing overcharge/deep discharge, and protecting against short circuits and temperature extremes."},{"step":"Discharging to Loads","description":"At night or during grid outages, the BESS supplies stored DC power through a bidirectional inverter, converting it to 230 V AC for your home or business."},{"step":"Grid Charging (Optional)","description":"When solar is insufficient, the BESS can charge from the grid during off-peak hours (typically overnight) at lower rates, then discharge during expensive peak periods — a strategy called time-of-use (TOU) optimization."},{"step":"Seamless Transfer","description":"During a blackout, a quality hybrid inverter switches to battery power in under 20 milliseconds — so fast that most electronics, routers, and computers never notice an interruption."}]',
  '[{"iconName":"Zap","title":"24/7 Power Supply","description":"Discharge stored solar energy through the night. A 10 kWh battery can power a typical Filipino household for 8–12 hours depending on load."},{"iconName":"ShieldCheck","title":"Brownout Immunity","description":"Visayas experiences some of the highest grid interruption rates in the Philippines. BESS eliminates disruption to sensitive equipment, refrigeration, and business operations."},{"iconName":"Clock","title":"Time-of-Use Savings","description":"Charge at night when rates are lowest; discharge during peak hours when rates are highest. Maximizes financial return even without heavy solar generation."},{"iconName":"Leaf","title":"Maximize Solar Self-Consumption","description":"Without storage, excess midday solar is wasted or exported at low credit rates. BESS captures this energy for self-use, maximizing your return on the solar investment."},{"iconName":"Flame","title":"LFP Safety","description":"Lithium iron phosphate (LFP) cells are thermally stable — they do not experience thermal runaway at the temperatures common in Philippine climates, unlike older NMC chemistries."},{"iconName":"CalendarCheck","title":"Long Lifespan","description":"LFP batteries are warranted for 10 years and rated for over 4,000 full cycles — meaning daily cycling for over 10 years before reaching 80% residual capacity."}]',
  '[{"item":"Homes and businesses in areas with frequent brownouts (Leyte, Samar, Cebu, Mindanao)"},{"item":"Cold storage facilities and refrigeration-dependent businesses"},{"item":"Hospitals, clinics, and medical facilities requiring uninterrupted power"},{"item":"Data centers, server rooms, and telecommunications equipment"},{"item":"Farms and agricultural operations with pumping and irrigation needs"}]',
  '[{"label":"Battery Chemistry","value":"Lithium Iron Phosphate (LFP)"},{"label":"Typical Capacity","value":"5 kWh – 200 kWh+"},{"label":"Round-Trip Efficiency","value":"95–98%"},{"label":"Depth of Discharge (DoD)","value":"Up to 90% usable"},{"label":"Cycle Life","value":">4,000 cycles at 80% DoD"},{"label":"Warranty","value":"10 years or 4,000 cycles"},{"label":"Operating Temperature","value":"0°C – 55°C"},{"label":"Supported Brands","value":"LVTOPSUN, Sunri, Sofar BTS"}]',
  '[{"title":"Battery Storage Technology Basics","url":"https://www.nrel.gov","publisher":"NREL"},{"title":"Electricity Storage and Renewables","url":"https://www.irena.org","publisher":"IRENA"},{"title":"Global EV Outlook — Battery Technology","url":"https://www.iea.org","publisher":"International Energy Agency (IEA)"},{"title":"LFP Battery Technology Overview","url":"https://www.sofarsolar.com","publisher":"Sofar Solar"}]'
FROM services s WHERE s.slug = 'bess'
ON CONFLICT (service_id) DO NOTHING;

-- pump
INSERT INTO service_details (service_id, tagline, overview, what_is_it, how_it_works, benefits, use_cases, specs, sources)
SELECT
  s.id,
  'Power your irrigation and water supply with the sun — zero fuel, zero electricity bill.',
  'Solar pumping systems use photovoltaic panels to power water pumps for irrigation, livestock watering, domestic supply, and fish pond management — eliminating diesel or electricity costs entirely. They are ideal for farms and remote properties in Eastern Visayas where fuel prices and grid unreliability make traditional pumping expensive.',
  $$A solar pumping system consists of a solar array, a solar pump controller (also called a VFD or MPPT pump drive), and a water pump (submersible, surface, or centrifugal). The controller converts solar DC power to variable-frequency AC to drive the pump motor, adjusting pump speed in real time based on available sunlight. No batteries are required — the pump simply runs whenever there is sufficient sun, storing energy in the form of water in a tank or pond. For overnight or cloudy-day operation, a small battery bank or grid backup can be added. These systems are promoted by the FAO and World Bank as a cost-effective solution for smallholder farmers in developing nations.$$,
  '[{"step":"Solar Panel Array","description":"Panels are sized to the pump motor''s power rating. A 1 kW submersible pump typically needs 1.5–2 kWp of panels to account for losses and operate under partial cloud."},{"step":"MPPT Pump Controller","description":"The controller tracks the maximum power point of the solar array and converts it to the right voltage and frequency for the pump motor. It also provides dry-run protection and fault monitoring."},{"step":"Water Pumping","description":"The pump lifts water from a well, river, or pond. Submersible pumps are used for deep wells (10–100 m+); surface pumps for shallow sources. Flow rate depends on pump size and solar availability."},{"step":"Storage Tank Buffering","description":"Water is pumped during daylight into an elevated tank or reservoir, providing gravity-fed supply throughout the day and night without batteries."}]',
  '[{"iconName":"Fuel","title":"Zero Fuel Cost","description":"Diesel pump operators in Eastern Visayas spend ₱500–₱2,000 per day on fuel. Solar pumping eliminates this cost entirely — the sun is free."},{"iconName":"Leaf","title":"Eco-Friendly Irrigation","description":"No emissions, no noise, no diesel spills. Solar pumps protect the surrounding soil and water table from fuel contamination."},{"iconName":"Wrench","title":"Low Maintenance","description":"Solar pump systems have fewer moving parts than diesel engines. With no combustion components, service intervals are minimal — typically an annual inspection."},{"iconName":"MapPin","title":"Works Anywhere","description":"No grid connection required. Ideal for farms, highlands, and coastal areas in Leyte, Samar, and surrounding islands where grid access is limited or unreliable."},{"iconName":"Sprout","title":"Supports Food Security","description":"Reliable, affordable irrigation enables year-round cropping instead of rain-fed farming — directly increasing harvest yields and farm income."},{"iconName":"Banknote","title":"Fast Payback","description":"At ₱1,000/day in diesel savings, a ₱150,000 solar pump system pays back in under 6 months for continuous-use agricultural applications."}]',
  '[{"item":"Rice and vegetable irrigation in Leyte, Samar, and surrounding islands"},{"item":"Coconut plantation irrigation and fertilizer injection"},{"item":"Livestock and poultry farm water supply"},{"item":"Fishpond water circulation and oxygenation"},{"item":"Domestic water supply for remote barangays without grid power"},{"item":"Community water systems and Level II water supply projects"}]',
  '[{"label":"Pump Types","value":"Submersible, Surface, Centrifugal"},{"label":"Motor Power Range","value":"0.37 kW – 22 kW+"},{"label":"Max Head (Submersible)","value":"Up to 200 m"},{"label":"Flow Rate","value":"1 m³/hr – 100 m³/hr depending on size"},{"label":"Controller Type","value":"MPPT Variable Frequency Drive (VFD)"},{"label":"Panel Requirement","value":"~1.5× pump motor rated power"},{"label":"Battery Optional","value":"Yes — for cloudy/night operation"},{"label":"Supported Brands","value":"Lorentz, Franklin, Grundfos solar series"}]',
  '[{"title":"Solar Powered Irrigation Systems","url":"https://www.fao.org","publisher":"Food and Agriculture Organization (FAO)"},{"title":"Solar Water Pumping for Agriculture","url":"https://www.worldbank.org","publisher":"World Bank"},{"title":"Solar Pumping Fundamentals","url":"https://www.irena.org","publisher":"IRENA"},{"title":"Philippine Solar Irrigation Program","url":"https://www.da.gov.ph","publisher":"Department of Agriculture Philippines"}]'
FROM services s WHERE s.slug = 'pump'
ON CONFLICT (service_id) DO NOTHING;

-- ev
INSERT INTO service_details (service_id, tagline, overview, what_is_it, how_it_works, benefits, use_cases, specs, sources)
SELECT
  s.id,
  'Charge your electric vehicle at home using clean solar energy — for almost nothing per kilometer.',
  'With the rapid growth of electric vehicles (EVs) in the Philippines, having a dedicated home or business EV charging station is no longer a luxury — it is a practical necessity. When paired with solar panels, you can charge your vehicle with energy that costs a fraction of the grid rate, making every kilometer essentially free.',
  $$An EV charger (Electric Vehicle Supply Equipment or EVSE) is a device that safely delivers AC or DC power to an electric vehicle's onboard charger or battery pack. Home and commercial chargers are classified by level: Level 1 (standard 230 V outlet, slow), Level 2 (dedicated 7–22 kW AC charger, fast), and Level 3 (DC fast charger, 50–350 kW, commercial). JMC Solar PH specializes in Level 2 AC wall-box installations for homes and businesses — the sweet spot of cost, convenience, and charging speed. When combined with an existing solar system, an EV charger effectively turns your car's fuel cost into a near-zero solar-powered expense.$$,
  '[{"step":"Dedicated Circuit Installation","description":"A licensed electrician installs a dedicated 32 A or 40 A circuit from your distribution board to the charger location — typically the garage or carport."},{"step":"Wall-Box Charger Mounting","description":"The EVSE unit is wall-mounted, weatherproofed (IP54+), and connected to the dedicated circuit. It includes safety features: ground fault protection, over-current protection, and thermal monitoring."},{"step":"Vehicle Connection via J1772 or Type 2","description":"The charger supplies AC power through a standardized connector. The vehicle''s onboard charger converts AC to DC for the battery pack. Communication between charger and vehicle manages safe charge limits."},{"step":"Solar Integration (Optional)","description":"When paired with a solar + BESS system, the EV charger can be configured to prioritize solar charging — charging your car only when solar excess is available, maximizing free energy use."}]',
  '[{"iconName":"Zap","title":"Fast Home Charging","description":"A 7.4 kW Level 2 charger adds roughly 30–40 km of range per hour — a full overnight charge covers 200–350 km for most EVs on the market."},{"iconName":"Banknote","title":"Solar-Powered Driving","description":"With solar panels, charging cost drops to ₱0 per km from solar, vs. ₱1.50–₱2.50 per km from the grid and ₱4–₱7 per km from petrol."},{"iconName":"Shield","title":"Safe & Standards-Compliant","description":"Proper EVSE installation prevents the risks of using standard outlets (overheating, fire). All installations comply with the Philippine Electrical Code (PEC) and IEC 61851."},{"iconName":"Smartphone","title":"Smart Charging Controls","description":"Schedule charging for off-peak hours or solar surplus periods via mobile app. Monitor energy used, cost savings, and charging history."},{"iconName":"Building2","title":"Property Value","description":"EV charging capability is increasingly a key selling point for residential and commercial properties as EV adoption accelerates in the Philippines."},{"iconName":"Globe","title":"Zero Local Emissions","description":"EV + solar = zero tailpipe emissions and zero carbon charging. Contribute directly to the Philippines'' NDC targets and clean air goals."}]',
  '[{"item":"Homeowners with EVs (BYD, Nissan Leaf, MG ZS EV, etc.) wanting convenient home charging"},{"item":"Businesses providing charging amenities for customers or employees"},{"item":"Hotels, resorts, and commercial establishments attracting EV-driving guests"},{"item":"Fleet operators (delivery vans, company cars) centralizing overnight charging"},{"item":"Solar system owners wanting to maximize self-consumption through EV charging"}]',
  '[{"label":"Charger Level","value":"Level 2 AC (standard home/commercial)"},{"label":"Output Power","value":"7.4 kW (32 A) – 22 kW (32 A, 3-phase)"},{"label":"Connector Standard","value":"IEC 62196 Type 2 / J1772 Type 1"},{"label":"Charging Speed","value":"~30–120 km of range per hour"},{"label":"Protection Rating","value":"IP54 minimum (outdoor rated)"},{"label":"Electrical Requirement","value":"Dedicated 32 A – 40 A circuit"},{"label":"Smart Features","value":"App control, scheduling, solar integration"},{"label":"Standards Compliance","value":"IEC 61851, Philippine Electrical Code"}]',
  '[{"title":"Global EV Outlook 2024","url":"https://www.iea.org","publisher":"IEA"},{"title":"Electric Vehicle Charging Infrastructure","url":"https://www.nrel.gov","publisher":"NREL"},{"title":"EV Adoption in Southeast Asia","url":"https://www.irena.org","publisher":"IRENA"},{"title":"Electric Vehicle Industry Development Act (RA 11697)","url":"https://www.doe.gov.ph","publisher":"DOE Philippines"}]'
FROM services s WHERE s.slug = 'ev'
ON CONFLICT (service_id) DO NOTHING;

-- ups
INSERT INTO service_details (service_id, tagline, overview, what_is_it, how_it_works, benefits, use_cases, specs, sources)
SELECT
  s.id,
  'Protect your equipment and keep critical operations running through every power interruption.',
  'An Uninterruptible Power Supply (UPS) provides instant battery backup when mains power fails or fluctuates. It protects sensitive electronics from voltage surges, brownouts, and blackouts — safeguarding computers, servers, medical devices, and industrial equipment from data loss, damage, and costly downtime.',
  $$A UPS is a device containing a battery (or battery bank), a rectifier/charger, and an inverter. It sits between the utility power supply and your connected loads. When grid power is normal, the UPS charges its battery while powering the connected load — in some topologies, through the inverter at all times (online/double-conversion), providing complete isolation from grid power quality issues. When power fails, the inverter seamlessly switches to battery power with zero to near-zero transfer time. UPS systems range from small desktop units (500 VA) to large three-phase industrial installations (hundreds of kVA). For solar hybrid users, a UPS complements the solar system by protecting loads during the brief inverter switching time and filtering power quality issues.$$,
  '[{"step":"Normal Operation","description":"Grid AC powers the load. In offline/standby UPS: power flows directly through the unit. In online/double-conversion: all power is rectified to DC and re-inverted to clean AC, providing total isolation."},{"step":"Battery Charging","description":"An internal rectifier and charger keeps the battery bank fully charged at all times, ready for instant deployment."},{"step":"Power Failure Response","description":"When mains power is interrupted, the UPS''s internal inverter supplies battery power to connected loads. Offline UPS transfer time: 4–12 ms. Online UPS: 0 ms (no transfer at all)."},{"step":"Voltage Regulation","description":"Many UPS models include AVR (Automatic Voltage Regulation), correcting brownouts and overvoltages without switching to battery — extending battery life and protecting equipment from power quality issues common in Philippine grids."},{"step":"Load Shedding & Runtime","description":"Runtime depends on battery capacity and connected load. A 1 kVA UPS with standard battery provides ~10–20 minutes for a PC. Extended battery modules can provide hours of runtime for critical loads."}]',
  '[{"iconName":"Monitor","title":"Equipment Protection","description":"Prevents expensive damage to computers, servers, medical equipment, and industrial controllers caused by voltage spikes, surges, and unclean power."},{"iconName":"Database","title":"Data & Work Protection","description":"Provides enough time to save work and perform a clean system shutdown during extended outages — preventing data corruption and hardware damage from abrupt power loss."},{"iconName":"Activity","title":"Business Continuity","description":"For businesses, every minute of downtime has a cost. A UPS ensures operations continue through the brief, frequent brownouts common in Visayas."},{"iconName":"Gauge","title":"Power Quality Conditioning","description":"Line-interactive and online UPS models regulate voltage continuously, correcting brownouts and overvoltages without battery cycling — crucial in areas with unstable grid voltage."},{"iconName":"Wifi","title":"Network & Internet Uptime","description":"Keep your routers, switches, and fiber ONTs powered through outages for continuous internet and communication — critical for home offices and remote workers."},{"iconName":"Zap","title":"Solar System Complement","description":"In a solar hybrid setup, a UPS covers the brief (<20 ms) switching window of the hybrid inverter during blackouts, providing completely seamless power for sensitive electronics."}]',
  '[{"item":"Home offices and remote workers (PC, router, monitors)"},{"item":"Medical clinics and pharmacies (refrigerators, diagnostic equipment)"},{"item":"CCTV systems and security infrastructure"},{"item":"Network server rooms and data centers"},{"item":"POS systems and retail cash registers"},{"item":"Industrial control panels and automation equipment"}]',
  '[{"label":"UPS Topologies","value":"Offline/Standby, Line-Interactive, Online (Double-Conversion)"},{"label":"Capacity Range","value":"500 VA – 500 kVA"},{"label":"Transfer Time (Offline)","value":"4–12 milliseconds"},{"label":"Transfer Time (Online)","value":"0 milliseconds"},{"label":"Battery Type","value":"VRLA AGM (standard), Lithium-Ion (premium)"},{"label":"Typical Runtime (1 kVA, full load)","value":"10–20 minutes (ext. battery: hours)"},{"label":"Efficiency (Online)","value":"94–97% (eco mode up to 99%)"},{"label":"Supported Brands","value":"Voltronic Power, APC, Eaton, Mecer"}]',
  '[{"title":"Uninterruptible Power Supplies — Technical Overview","url":"https://www.iec.ch","publisher":"International Electrotechnical Commission (IEC)"},{"title":"Power Quality and UPS Systems","url":"https://www.nrel.gov","publisher":"NREL"},{"title":"Voltronic Power UPS Technical Documentation","url":"https://www.voltronicpower.com","publisher":"Voltronic Power"},{"title":"Business Continuity and Power Protection","url":"https://www.iea.org","publisher":"IEA"}]'
FROM services s WHERE s.slug = 'ups'
ON CONFLICT (service_id) DO NOTHING;

-- controller
INSERT INTO service_details (service_id, tagline, overview, what_is_it, how_it_works, benefits, use_cases, specs, sources)
SELECT
  s.id,
  'The intelligent regulator that protects your batteries and maximizes the energy harvested from your solar array.',
  'A solar charge controller is the critical device between your solar panels and battery bank. It regulates the voltage and current coming from the panels to safely charge the batteries, preventing overcharge and deep discharge — the two main causes of premature battery failure. Modern MPPT controllers also maximize energy harvest by up to 30% compared to older PWM technology.',
  $$A solar charge controller (SCC) sits in the DC circuit between the solar array and the battery bank. It has two primary functions: (1) preventing overcharge by reducing or stopping charge current when the battery reaches full charge, and (2) preventing reverse current flow from battery to panels at night. There are two main controller technologies: PWM (Pulse Width Modulation) — the older, simpler, less efficient technology; and MPPT (Maximum Power Point Tracking) — the modern standard that continuously adjusts its input voltage to extract the maximum available power from the solar array. MPPT controllers are particularly beneficial when panels operate at a higher voltage than the battery bank, allowing them to step down voltage while increasing current, improving harvest efficiency by 15–30%.$$,
  '[{"step":"Array Voltage Sensing","description":"The MPPT controller continuously measures the voltage and current output of the solar array, mapping the power curve (I-V curve) to find the exact operating point with maximum power output."},{"step":"Maximum Power Point Tracking","description":"The controller adjusts its input impedance several times per second to stay at the maximum power point — even as sunlight intensity and panel temperature change throughout the day."},{"step":"DC-DC Conversion","description":"The MPPT controller performs a DC-DC step-down (buck) conversion: it accepts higher panel voltage (e.g. 60–150 V) and outputs at the battery''s required charge voltage (12 V / 24 V / 48 V), with the extra voltage converted to additional current."},{"step":"Multi-Stage Battery Charging","description":"The controller applies a multi-stage charging profile: Bulk (full current), Absorption (constant voltage, tapering current), and Float (trickle maintenance). This optimizes battery health and longevity."},{"step":"Low-Voltage Disconnect (LVD)","description":"When battery voltage drops below a set threshold, the LVD output disconnects loads automatically — preventing deep discharge, which is the leading cause of premature battery failure."}]',
  '[{"iconName":"Battery","title":"Battery Protection","description":"Proper charge regulation doubles or triples battery lifespan by preventing overcharge and deep discharge — the two most damaging operating conditions."},{"iconName":"TrendingUp","title":"Up to 30% More Energy","description":"MPPT tracking extracts 15–30% more energy from the same panel array compared to PWM controllers — particularly valuable in cloudy or partially shaded conditions."},{"iconName":"Sliders","title":"Flexible System Voltage","description":"MPPT controllers allow high-voltage panel strings (series wiring) to charge lower-voltage battery banks — enabling longer cable runs with thinner wire, reducing installation cost."},{"iconName":"Sun","title":"All-Day Optimization","description":"MPPT tracking adapts continuously as the sun angle, cloud cover, and panel temperature change — maximizing harvest from dawn to dusk, not just at peak noon output."},{"iconName":"Smartphone","title":"Monitoring & Diagnostics","description":"Modern controllers include LCD displays and Bluetooth/RS485 connectivity for real-time monitoring of array power, battery voltage, state of charge, and historical data logging."},{"iconName":"Wrench","title":"Plug-and-Play Compatibility","description":"Compatible with all battery types — lead-acid (flooded, AGM, gel) and lithium (LFP, lithium polymer) — with programmable charge parameters for optimal battery chemistry matching."}]',
  '[{"item":"Off-grid solar systems for homes, farms, and remote installations"},{"item":"Solar streetlights and outdoor lighting systems"},{"item":"Telecommunications repeater stations and remote monitoring equipment"},{"item":"Solar-powered boats, RVs, and mobile installations"},{"item":"Small standalone systems: water pumps, sensors, security cameras"},{"item":"Battery charging stations in remote barangays"}]',
  '[{"label":"Controller Types","value":"MPPT (recommended), PWM"},{"label":"MPPT Efficiency","value":">98% tracking efficiency"},{"label":"Current Range","value":"10 A – 100 A (MPPT), 5 A – 60 A (PWM)"},{"label":"System Voltages","value":"12 V / 24 V / 36 V / 48 V auto-select"},{"label":"Max PV Input Voltage","value":"Up to 150 V (MPPT)"},{"label":"Battery Compatibility","value":"Lead-Acid, AGM, Gel, LFP Lithium"},{"label":"Protection Features","value":"Overcharge, deep discharge, reverse polarity, short circuit"},{"label":"Supported Brands","value":"Victron Energy, EPSolar, Sofar, Renogy"}]',
  '[{"title":"Photovoltaic Systems — Charge Controller Design","url":"https://www.nrel.gov","publisher":"NREL"},{"title":"MPPT Solar Charge Controller Technology","url":"https://www.victronenergy.com","publisher":"Victron Energy"},{"title":"Off-Grid Solar for Developing Nations","url":"https://www.irena.org","publisher":"IRENA"},{"title":"Solar Home Systems — Technical Standards","url":"https://www.iea.org","publisher":"IEA"}]'
FROM services s WHERE s.slug = 'controller'
ON CONFLICT (service_id) DO NOTHING;
